### PR TITLE
AccommodationFinder component: code provided

### PR DESCRIPTION
**Pull request by MrVannu**
In this pull request, I have added the code developed by me (Vannuccini Luca) and my colleague (Fazzi Violetta) for the Accommodation Finder web component developed during the Open Data Hub Day 2025 in Bolzano, Italy.

### CODE REVIEW

**Comment by RudiThoeni** [comment]
Hi @MrVannu 
I cannot merge this PR because it overwrites all changes i made to your webcomponent...... all the code in the index.html i had to  integrate into the js.....
However i managed to deploy it https://webcomponents.opendatahub.testingmachine.eu/webcomponent/Accommodation%20Finder
so i will close this PR 
cheers
Rudi

**Comment by MrVannu** [comment]
Buongiorno,

La ringrazio per la Sua disponibilità.
Mi sa indicare il link dove posso trovare il componente pubblicato?
Dallo store non si trova.

Ringrazio anticipatamente,

Cordialmente,
Vannuccini Luca

**Comment by RudiThoeni** [comment]
It is published on the Test Store
https://webcomponents.opendatahub.testingmachine.eu/webcomponent/Accommodation%20Finder

**Comment by MrVannu** [comment]
Thank you a lot!

Have a nice day,

Luca

Il giorno mer 12 giu 2024 alle ore 15:11 RudiThoeni <
***@***.***> ha scritto:

**Pull request closed without merging**
